language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required
os:
  - osx
  - linux

notifications:
  email:
    on_success: never

branches:
  only:
    - master
addons:
  apt:
    packages:
      - ca-certificates
      - libnuma-dev
